export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";

export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_ERROR = "LOGIN_TEACHER_ERROR";
export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const EDIT_STUDENT_SUCCESS = " EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";

export const EDIT_TEACHER_SUCCESS = " EDIT_TEACHER_SUCCESS";
export const EDIT_TEACHER_REQUEST = "EDIT_TEACHER_REQUEST";
