export const GET_DOUBT_SUCCESS = " GET_DOUBT_SUCCESS";
export const GET_DOUBT_ERROR = "GET_DOUBT_ERROR";
export const GET_DOUBT_REQUEST = "GET_DOUBT_REQUEST";

export const DELETE_DOUBT_SUCCESS = " DELETE_DOUBT_SUCCESS";
export const DELETE_DOUBT_REQUEST = "DELETE_DOUBT_REQUEST";

export const GET_NOTICE_SUCCESS = " GET_NOTICE_SUCCESS";
export const GET_NOTICE_ERROR = "GET_NOTICE_ERROR";
export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";

export const GET_REPORT_DETAILS_SUCCESS =
  " GET_APPOINTMENT_DETAILS_SUCCESS";

export const GET_ALLDATA_SUCCESS = " GET_ALLDATA_SUCCESS";
export const GET_ALLDATA_REQUEST = "GET_ALLDATA_REQUEST";

export const DELETE_REPORT_SUCCESS = " DELETE_APPOINTMENT_SUCCESS";
